name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: | 
      try
      {
         $process = Start-Process `
         -FilePath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VSIXInstaller.exe" `
         -ArgumentList ("/quiet", '"C:\Program Files (x86)\Windows Kits\10\Vsix\VS2019\WDK.vsix"') `
         -Wait `
         -PassThru
     }
     catch
     {
         Write-Host "There is an error during WDK.vsix installation"
         $_
        exit 1
     }
     shell: pwsh
    - name: Run a multi-line script
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\usbip_win.sln
